[build]
  command = "next build && next export"
  functions = "./functions"

[context.branch-deploy.environment]
  NODE_ENV = "development"

[[headers]]
  for = "/:width/*"
  [headers.values]
    cache-control = '''
    public, 
    max-age=604800, 
    immutable'''

[[redirects]]
  from = "/:width/*"
  to = "/.netlify/functions/quokka-fetch"
  status = 200