[build]
  command = "next build && next export"
  functions = "./functions"

[context.branch-deploy.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/"
  to = "/"
  status = 200

[[redirects]]
  from = "/meet-the-quokkas"
  to = "/meet-the-quokkas"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/quokka-fetch"
  status = 200

