[build]
  command = "next build && next export"
  functions = "./functions"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  quokkaFunctionUrl = "http://localhost:34567/.netlify/functions/quokka-fetch/"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
    public, 
    max-age=604800, 
    immutable'''

[[redirects]]
  from = "/meet-the-quokkas"
  to = "/meet-the-quokkas"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/quokka-fetch/:splat"
  status = 200